default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ibedecgo_development

test:
  <<: *default
  database: ibedecgo_test

production:
  <<: *default
  database: ibedecgo_production
  username: ibedecgo
  password: <%= ENV["IBEDECGO_DATABASE_PASSWORD"] %>
