default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost

development:
  <<: *default
  database: ibedec_development

test:
  <<: *default
  database: ibedec_test

production:
  <<: *default
  database: ibedec_production
  username: ibedec
  password: <%= ENV["IBEDEC_DATABASE_PASSWORD"] %>
